version: "3.9"
services:
  db:
    image: postgres:16
    container_name: finoa_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: finoa
      POSTGRES_PASSWORD: finoa
      POSTGRES_DB: finoa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finoa -d finoa"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finoa_api
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - "3000:3000"
      - "4983:4983"  # Drizzle Studio Port
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app           
      - /app/node_modules

volumes:
  pgdata:
